config/routes.rb
Rails.application.routes.draw do

resources :listings

root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy, :index]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/new", to: 'listings#new'
  get "/success", to: 'listings#success'
  get "/book", to: 'listings#book'
  post "/book", to: 'listings#book'
  post "/pay", to: 'payments#new'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'tags/:tag', to: 'listings#index', as: :tag
  get '/search', to: 'listings#search'
  get '/payment', to: 'payments#new'
  post '/payments', to: 'payments#create'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
     belongs_to :user
			has_many :taggings
			has_many :tags, through: :taggings
			mount_uploaders :avatars, AvatarUploader
			acts_as_bookable preset: :room

def self.tagged_with(name)
  Tag.find_by(name: name).listings
end

def self.tag_counts
  Tag.select("tags.*, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
end

def tag_list
  tags.map(&:name).join(", ")
end

def tag_list=(names)
  self.tags = names.split(",").map do |n|
    Tag.where(name: n.strip).first_or_create!
  end
end
searchkick match: :word_start, searchable: [:title, :location]
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

   before_action :set_listing, only: [:show, :edit, :update, :destroy]
   skip_before_action :verify_authenticity_token

	def profile
		@my_listings = current_user.listings.paginate(:page => params[:page], :per_page => 5)
	end

  def new
  	@listing = Listing.new
  end

  def create
  		@listing=current_user.listings.new(listing_params)
      @listing.schedule = IceCube::Schedule.new(Date.today, duration: 1.day)
      @listing.schedule.add_recurrence_rule IceCube::Rule.daily
  	 	if @listing.save
    		redirect_to @listing
  		else
    		render :new
  		end
  end

  def edit
  end

  def search
    @listings = Listing.search(params[:term], fields: ["title", "location"], mispellings: {below: 5})
        if @listings.blank?
          redirect_to root_path, flash:{danger: "no successful search result"}
        else
          render :search
        end
    end

  def update
    @listing.update(listing_params)
      if @listing.save
        redirect_to @listing
      else 
        render :edit
      end
  end

  def show
    @listing = Listing.find(params[:id])
    @cbookings=@listing.bookings.paginate(:page => params[:page], :per_page => 3)
  end

  def book
    @listing = Listing.find(params[:id])
    from= Date.strptime(params[:from], "%m/%d/%Y")
    to= Date.strptime(params[:to], "%m/%d/%Y")
    amount=params[:amount].to_i
    price=params[:price].to_i
    if @listing.check_availability(time_start: from, time_end: to, amount: amount) == true
      @Acts_as_bookable_booking = @listing.be_booked! current_user, time_start: from, time_end: to, amount: amount, total_sum: price*(to.mjd-from.mjd)
        @host = @listing.user.email
        ReservationJob.perform_later(@Acts_as_bookable_booking,@host)
        redirect_to payment_path(@Acts_as_bookable_booking)
    else
        redirect_to @listing, flash:{danger: "You have either chosen a date that is not available or have too many people for this accomadation, please try again."}
    end
  end

  def success
    @Acts_as_bookable_booking = Acts_as_bookable_booking.find(params[:id])
    @listing= Listing.find(@Acts_as_bookable_booking.bookable_id)
  end


  def index
    if params[:tag]
      @listings = Listing.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5)
    else
      @listings = Listing.all.paginate(:page => params[:page], :per_page => 5)
    end
  end

  def destroy
    Tagging.where(listing_id: params[:id]).destroy_all
    Acts_as_bookable_booking.where(bookable_id: params[:id]).destroy_all
    @listing.destroy
    redirect_to listings_path
  end

  def tag
  end

  def listing_params
    params.require(:listing).permit(:title,:description,:tag_list,:capacity,:location,:price,{avatars:[]})
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

end


#render new will just load the erb straight away, redirect is go to action in controller and then render

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<head>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Lato", sans-serif;}
.w3-left, .w3-right, .w3-tag {cursor:pointer;}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px;}
</style>
</head>

    <%= form_for @listing do |f| %>
    <div class="w3-group">
   <%= f.label :title %><br>
     <%= f.text_field :title, :class=> "w3-input w3-border w3-hover-border-black" %>
     </div>
     <div class="w3-group">
   <%= f.label :description %><br>
     <%= f.text_field :description, :class=> "w3-input w3-border w3-hover-border-black"%>
     </div>
     <%= f.label :location %><br>
     <%= f.text_field :location, :class=> "w3-input w3-border w3-hover-border-black"%>
     <div class="w3-group">
     <%= f.label :capacity %><br>
     <%= f.number_field :capacity, :class=> "w3-input w3-border w3-hover-border-black"%>
     </div>
     <%= f.label :price %><br>
     <%= f.number_field :price, :class=> "w3-input w3-border w3-hover-border-black"%>
     <div class="w3-group">
     <%= f.label :tag_list, "Tags (separated by commas)" %><br>
     <%= f.text_field :tag_list, :class=> "w3-input w3-border w3-hover-border-black"%>
     </div>
     <div class="w3-group">
     <%= f.label :avatars,"Images:"%> <br>
     <%= f.file_field :avatars, multiple: true, :class=> "w3-input w3-border w3-hover-border-black" %>
     </div>

     <%= f.submit "Save changes",:class=> "w3-btn w3-btn-block w3-padding-12" %>
   <% end %>

app/views/listings/edit.html.erb
<head>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Lato", sans-serif;}
.w3-left, .w3-right, .w3-tag {cursor:pointer;}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px;}
</style>
</head>

<div class="w3-content w3-container" style="max-width:1100px;margin-descriptionp:80px;margin-botdescriptionm:80px">

<div class="w3-row-padding" style="margin:0 -16px" id="plans">
    <div class="w3-center w3-padding-64">
      <h3>Edit Listing</h3>
    </div>
<%= render 'form' %>

app/views/listings/index.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}
</style>
</head>

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:10px">
<h1 class="text-center"> All Listings </h1>
<br>
  <!-- The Grid -->
<div class="w3-row">
<% @listings.each do|x| %>
<div class="w3-container w3-card-2 w3-white w3-round w3-margin"><br>
<div class="text-center">
        <h4><b><%=x.title%></b></h4>
        <hr class="w3-clear">
        <p><b>Description:</b>
						<%=x.description%><br><br>
						<b>Location:</b>
						<%=x.location%><br><br>
						<b>Tags:</b>
						<%= raw x.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %><br>
						</p>
          <div class="w3-row-padding" style="margin:0 -16px">
		          <%if x.avatars[0] !=  nil%>
							<%= image_tag (x.avatars[0].medium.url) %>
							<%else%>
							No images yet!
							<% end %>
            </div><br>
        <b>Posted by:</b>
        <%= link_to x.user.name, user_path(x.user.id) %><br>
        <b><br>
        <%= link_to "View full listing", listing_path(x) %><br><br>
        </b>
        </div>
			</div>
		<br>
    <%end%>
   </div>
  <%= will_paginate @listings %>
</div>

<div class="row">
<footer>
<%= link_to "Home", root_path %>
</footer>
</div>

app/views/listings/new.html.erb
<head>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Lato", sans-serif;}
.w3-left, .w3-right, .w3-tag {cursor:pointer;}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px;}
</style>
</head>

<div class="w3-content w3-container" style="max-width:1100px;margin-descriptionp:80px;margin-botdescriptionm:80px">

<div class="w3-row-padding" style="margin:0 -16px" id="plans">
    <div class="w3-center w3-padding-64">
      <h3>New Listing</h3>
    </div>
<%= render 'form' %>

app/views/listings/search.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}
</style>
</head>

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:10px">
<h1 class="text-center"> Search Results </h1>
<br>
  <!-- The Grid -->
<div class="w3-row">
<% @listings.each do|x| %>
<div class="w3-container w3-card-2 w3-white w3-round w3-margin"><br>
<div class="text-center">
        <h4><b><%=x.title%></b></h4>
        <hr class="w3-clear">
        <p><b>Description:</b>
						<%=x.description%><br><br>
						<b>Location:</b>
						<%=x.location%><br><br>
						<b>Tags:</b>
						<%= raw x.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %><br>
						</p>
          <div class="w3-row-padding" style="margin:0 -16px">
		          <%if x.avatars[0] !=  nil%>
							<%= image_tag (x.avatars[0].medium.url) %>
							<%else%>
							No images yet!
							<% end %>
            </div><br>
        <b>Posted by:</b>
        <%= link_to x.user.name, user_path(x.user.id) %><br>
        <b><br>
        <button type="button" class="btn btn-primary"><%= link_to "View full listing", listing_path(x) %></button><br><br>
        </b>
        </div>
			</div>
		<br>
    <%end%>
   </div>
  <%= will_paginate @listings %>
</div>

<div class="row">
<footer>
<%= link_to "Home", root_path %>
</footer>
</div>

app/views/listings/show.html.erb
<head>
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Lato", sans-serif;}
.w3-left, .w3-right, .w3-tag {cursor:pointer;}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px;}
</style>
<script> 
$( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#from" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 3
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 3
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
  } );
  </script>
  </head>

<div class="w3-content w3-container" style="max-width:1100px;margin-top:80px;margin-bottom:80px">

  <div class="w3-section">
    <h1><b><%=@listing.title%></b></h1>
  </div>

 <div class="w3-display-container mySlides"> 
  <% if @listing.avatars?%>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <%for i in 0..@listing.avatars.count - 1 %>
          <li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
          <%end%>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @listing.avatars.each_with_index do |avatar, index|%>
          <div class="item <%= 'active' if index == 0%>">
            <%= image_tag (avatar.large.url) %>
          </div>
          <%end%>
      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">	
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <%else%>
  <div class="text-center">
  No images yet!
  </div>
  <%end%>
</div>


<div class="w3-row">
    <div class="w3-center w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Details</span>
    </div>
    <div class="w3-col l3 m6 w3-light-grey w3-padding-large">
      <h3>Listing Name:</h3>
      <p><%=@listing.title%></p>
    </div>

    <div class="w3-col l3 m6 w3-grey w3-padding-large">
      <h3>Description:</h3>
      <p><%=@listing.description%></p>
    </div>

    <div class="w3-col l3 m6 w3-dark-grey w3-padding-large">
      <h3>Location:</h3>
      <p><%=@listing.location%></p>
    </div>

    <div class="w3-col l3 m6 w3-black w3-padding-large">
      <h3>Tags</h3>
      <% if @listing.tag_list == "" %>
      <p>No tags yet!</p>
      <% else %>
      <p><%= @listing.tag_list%></p>
      <%end%>
    </div>
  </div>


<% if @msg%>
<div class="row" >
<div class ="col-md-12">
<%= @msg %> 
</div>
</div>
<%end%>

<%if @listing.user != current_user%>
  <div class="w3-row-padding" style="margin:0 -16px" id="plans">
    <div class="w3-center w3-padding-64">
      <h3>Booking Form</h3>
      <p>Check for availability below, no two occupants can share the same timespan.</p>
    </div>
	 <form method=post action='/book'>
   <div class="w3-group">
		<label for="from">From:</label>
		<input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" id="from" name="from">
  </div>
  <div class="w3-group">
		<label for="to">To:</label>
		<input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" id="to" name="to">
  </div>
  <div class="w3-group">
		<label for="amount">Number of people:</label>
		<input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="number" id="amount" name="amount">
  </div>
  <div class="w3-group">
		<input type="hidden" name="id" value=<%=@listing.id%> >
    <input type="hidden" name="price" value=<%=@listing.price%> >
  </div>
		<input class="w3-btn w3-btn-block w3-padding-12" type="submit" value="Submit">
	</form>
    <% end %>
</div>

<div class="w3-row-padding" style="margin:0 -16px" id="about">
<div class="w3-center w3-padding-64">
  <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Bookings</span>
  </div>
<div class="row">
  <%if @listing.bookings.count > 0 %>
  	<%@cbookings.each do |x|%>
    <div class="w3-third w3-margin-bottom">
      <ul class="w3-ul w3-border w3-center w3-hover-shadow">
      <li class="w3-black w3-xlarge w3-padding-32"><%=x.id%></li>
        <li class="w3-padding-16"><b>Booking by: </b><%=x.booker.name%></li>
        <li class="w3-padding-16"><b>From: </b><%=x.time_start.to_date%></li>
        <li class="w3-padding-16"><b>Till: </b><%=x.time_end.to_date%></li>
      </ul>
    </div>
	 <%end%>
   </div>
   <div class="row">
   <div class="text-center"> <%= will_paginate @cbookings %> </div>
   </div>
  <% elsif currrent_user=@listing.user && @listing.bookings.count == 0%>
  <div class="w3-third w3-margin-bottom">
  </div>
  <div class="w3-third w3-margin-bottom">
      <ul class="w3-ul w3-border w3-center w3-hover-shadow">
      <li class="w3-black w3-xlarge w3-padding-32">No bookings yet!</li>
    </ul>
    </div>
    <div class="w3-third w3-margin-bottom">
    </div>
    <br>
  <% else %>
  <div class="w3-third w3-margin-bottom">
  </div>
      <div class="w3-third w3-margin-bottom">
      <ul class="w3-ul w3-border w3-center w3-hover-shadow">
      <li class="w3-black w3-xlarge w3-padding-32">No bookings yet! Fill in above fields to book!</li>
    </ul>
    </div>
    <div class="w3-third w3-margin-bottom">
    </div>
  <%end%>
  </div>
  </div>

<div class="row">
  <footer class="w3-container w3-padding-32 w3-light-grey w3-center">
  <%= link_to "Home", root_path %>
  <br>
  <% if @listing.user == current_user %>
  <%= link_to "Edit", edit_listing_path(@listing) %><br>
  <%= link_to "Delete", listing_path(@listing), method: :delete %><br>
  <%end%>
  </footer>
  </div>

app/views/listings/success.html.erb
<h1> Booking confirmed! </h1>
<h4> Details </h4>

<ul class="list-group">
  <li class="list-group-item">
    <p>Listing name: <%= link_to @listing.title, listing_path(@listing) %></p>
    <p>No. of Guests: <%= @Acts_as_bookable_booking.amount%> </p>
    <p>Check-in Date: <%= @Acts_as_bookable_booking.time_start %></p>

    <p>Checkout Date: <%= @Acts_as_bookable_booking.time_end %></p>

    <strong>Payment Status:</strong>
      <% if @Acts_as_bookable_booking.payments.where(status: :authorized).count == 0%>
      <span class="btn btn-danger"> NOT PAID </span>

       <%= link_to 'Pay Now' , pay_path(@Acts_as_bookable_booking.id.to_s), class: "btn btn-warning"  %>
      <% else %>
      <span class="btn btn-success">PAID</span>
      <% end %>
  </li>
</ul>

<%= link_to "Back to Listing", listing_path(@listing)%>