config/routes.rb
Rails.application.routes.draw do

resources :listings

root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy, :index]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/new", to: 'listings#new'
  get "/success", to: 'listings#success'
  get "/book", to: 'listings#book'
  post "/book", to: 'listings#book'
  post "/pay", to: 'payments#new'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'tags/:tag', to: 'listings#index', as: :tag
  get '/search', to: 'listings#search'
  get '/payment', to: 'payments#new'
  post '/payments', to: 'payments#create'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  mount_uploaders :avatars, AvatarUploader

has_many :authentications, :dependent => :destroy
has_many :listings
acts_as_booker

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    name = user_params.delete(:name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.name = name
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


before_action :set_user, only: [:show,:update]
skip_before_action :verify_authenticity_token

	def show
	end

	def index
		@user=User.all.paginate(:page => params[:page], :per_page => 5)
	end

	def edit
	end

	def update
		@user.update(user_params)
		 if @user.save
		redirect_to @user
	end
	end
	
	private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
    params.require(:user).permit(:name,:email,{avatars:[]})
  end

end

app/views/users/_form.html.erb
<div class="text-center">
<div class="name-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
</div>

app/views/users/index.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Open Sans", sans-serif}
</style>
</head>

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:10px">
<h1 class="text-center"> All Users </h1>
<br>

  <!-- The Grid -->
<div class="w3-row">
<% @user.each do|x| %>
<div class="w3-container w3-card-2 w3-white w3-round w3-margin"><br>
<div class="text-center">
        <h4><b><%=x.name%></b></h4>
        <hr class="w3-clear">
        <p><b>Email:</b>
						<%=x.email%>
						</p><br>
        <%= link_to "Check out profile", user_path(x) %><br><br>
</div>
</div>
   <%end%>
  <%= will_paginate @user %>
</div>
</div>

<div class="row">
<footer>
<%= link_to "Home", root_path %>
</footer>
</div>

app/views/users/new.html.erb
<div class="text-center">
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit(:submit) %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %> 
    </div>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
</head>

<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-container w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding" style="margin:0 -16px">
  
    <!-- Left Column -->
    <div class="w3-third">
      <div class="w3-card-2 w3-round w3-white">
        <div class="w3-container">
        <h4 class="w3-center"><%=@user.name%></h4>
        <p class="w3-center">
          <%if @user.avatars[0] !=  nil%>
              <%= image_tag (@user.avatars[0].medium.url) %>
              <%else%>
              No images yet, click below to upload!
              <% end %>
              </p>
              <hr>
          <div class="w3-display-bottomleft w3-container w3-text-black">
          </div>
        </div>
        <div class="w3-container">
          <p><i cclass="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i><%=@user.name%></p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%=@user.email%></p>
          <%if @user==current_user%>
          <p>
        <%= form_for @user do |f| %>
        <div class="w3-group">
        <%= f.label :avatars,"Choose a profile pic:"%> <br>
        <%= f.file_field :avatars, multiple: true, :class=> "w3-input w3-border w3-hover-border-black" %>
        </div>
        <%= f.submit "Save changes",:class=> "w3-btn w3-btn-block w3-padding-12" %>
        <% end %>
    		</p>
        <%end%>
          <hr>
        </div>
        </div>
        </div>


    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card-2 w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Listings</h2>
        <% if @user.listings.count == 0%>
        <h2> No listings yet!</h2>
        <%else%>
        <%@user.listings.each do |x| %>
        <div class="w3-container">
          <h5 class="w3-opacity"><b><%=x.title%></b></h5>
          <h6 class="w3-text-teal">Tags:<span class="w3-tag w3-teal w3-round"><%= raw x.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></span></h6>
          <p><%=x.description%></p>
          <%if x.avatars[0] !=  nil%>
						<%= image_tag (x.avatars[0].square.url) %>
						<%else%>
						No images yet!
						<% end %>
            <br><br>
            <p><%= link_to "View listing", listing_path(x) %></p>
						<hr>
						</div>
          <% end %>
          <hr>
        </div>
        <%end%>
			
			<div class="w3-container w3-card-2 w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Reservations</h2>
        <% if @user.bookings.count == 0%>
        <h2> No reservations yet!</h2>
        <%else%>
        <%@user.bookings.each do |x| %>

        <div class="w3-container">
          <h5 class="w3-opacity"><b><%=x.bookable.title%></b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>From <%=x.time_start.to_date%> till <%=x.time_end.to_date%></h6>
          <p><%= link_to "View listing", listing_path(x.bookable) %></p>
          <hr>
        </div>
      <%end%>
      <%end%>
      </div>

      </div>
    </div>
  </div>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p><%= link_to "Back to Users", users_path %></p>
</footer>

</body>