config/routes.rb
Rails.application.routes.draw do

resources :listings

root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy, :index]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/new", to: 'listings#new'
  get "/success", to: 'listings#success'
  get "/book", to: 'listings#book'
  post "/book", to: 'listings#book'
  post "/pay", to: 'payments#new'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'tags/:tag', to: 'listings#index', as: :tag
  get '/search', to: 'listings#search'
  get '/payment', to: 'payments#new'
  post '/payments', to: 'payments#create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<body>

<div style="left: 0px; top: 0px; overflow: hidden; margin: 0px; padding: 0px; height: 100%; width: 100%; z-index: -999999; position: fixed;">
<img src="http://pairbnb.herokuapp.com/landing4.jpg" style="position: absolute; margin: 0px; padding: 0px; border: medium none; width: 100%; height: 100%; max-height: none; max-width: none; z-index: -999999; left: 0px; top: -71.92px;">
</div>

<div class="text-center" id="functions">
      <div>PairBnB</h1>
        <p>
			<div class="row" id="listings">
			<%= link_to "Create New Listing", new_listing_path %>
			|
			<%= link_to "Show all Listings", listings_path %>
			|
			<%= link_to "Show all Users", users_path %>
			</div>
		</p>
    </div>
</div>

</body>