config/routes.rb
Rails.application.routes.draw do

resources :listings

root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy, :index]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/new", to: 'listings#new'
  get "/success", to: 'listings#success'
  get "/book", to: 'listings#book'
  post "/book", to: 'listings#book'
  post "/pay", to: 'payments#new'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'tags/:tag', to: 'listings#index', as: :tag
  get '/search', to: 'listings#search'
  get '/payment', to: 'payments#new'
  post '/payments', to: 'payments#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application.css' %>
  <%= javascript_include_tag 'application.js' %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    "acts_as_bookable/application", media: "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pairbnb</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Pairbnb</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
        <li> <% if signed_in? %>
            <%= link_to "Profile", user_path(current_user) %>
            <% end %></li>
      </ul>

      <form class="navbar-form navbar-left" method=get action='/search'>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Locations" name="term"> 
        </div>
        <button type="submit" class="btn btn-default" value="search">Search</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li>    
          <% if current_user %>
          <div id="identity">
            Signed in as <strong><%= current_user.name %></strong>!
          </div>
          <% else %>
            <a class="btn btn-block btn-social btn-facebook" id="sign in" href="/auth/facebook">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            Sign in with Facebook
            </a>
          <% end %>
        </li>
        <li>
          <%if signed_in?%>
            <%= link_to "Log out", sign_out_path, method: :delete %>
          <%else%>
           <%= link_to "Sign in", sign_in_path %>
          <%end%>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <div class="text-center">
    <% flash.each do |key, value| -%>
      <div class="alert alert-<%= key %>"><%=h value %></div>
    <% end %>
 </div>
</nav>

  <%= yield %>
</html>